version: '3.4'

services:
  twitterbackend:
    image: kapil012002/twitter_backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    restart: "always"
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    restart: "always"